language: java
jdk:
  - oraclejdk8
sudo: false
cache:
  directories:
  - "$HOME/.m2"
  - "$HOME/.sonar/cache"
addons:
  sonarqube: true
install:
- mvn dependency:go-offline
script:
- mvn install site -Dmaven.test.failure.ignore=true
after_success:
- mvn sonar:sonar
